# Generated by Django 2.2 on 2019-04-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=200)),
                ('nomenclature', models.CharField(max_length=200)),
                ('id_api', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('state', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'station',
                'verbose_name_plural': 'stations',
                'unique_together': {('id_api',)},
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_bikes', models.PositiveIntegerField(default=0)),
                ('empty_slots', models.PositiveIntegerField(default=0)),
                ('date_api', models.DateTimeField()),
                ('date', models.DateTimeField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station', to='store.Station')),
            ],
            options={
                'verbose_name': 'data',
                'verbose_name_plural': 'data',
                'unique_together': {('date', 'station')},
            },
        ),
    ]
